# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac55c4875c3af6f71f36eb43b950fa7c74727a36243caa537a28f58ca43137d416547c931418c507b176059eca21fa7146f2e9387fc4a584c7b6bceeb3749c22

test:
  secret_key_base: b82c6cedfbd1cbabc9fef7eb04020ba0e7585b8f5643bc84492b06a91bbf375ef3664d2397941268ecd2a59cf61ba32737b18f2b0e7b5f464d4030df65ca7b3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
